apiVersion: v2
name: mychartV2
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: victoria-metrics-k8s-stack
    version: "0.45.0"
    repository: "https://victoriametrics.github.io/helm-charts"