apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort # Change service type to NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30002 # Write the access port (in range 30000-32767)